### ISSUE TITLE
Modus Table: row selection issue in storybook when density changes

### ISSUE THREAD

**Issue by yohernandez** [trimble-oss/modus-web-components#1983] opened 2023-12-27 15:45 UTC
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

There is an issue with the row selection when the density property changes. Steps to reproduce:

1. Select a few rows.
2. Change the density value
3. See the preselected rows are loaded
4. Select a row.
5. See the previous selected rows are selected again.

![checked issue](https://github.com/trimble-oss/modus-web-components/assets/48927186/5d840f66-7b8b-4c73-aa7b-3ca7a0efb6ac)

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

e-builder

### What is your team/division name ?

e-builder

### Are you willing to contribute ?

Yes

**Comment by apaddock** [comment] 2023-12-28 15:23
Also, the pagination change event is being triggered by the change to density. 
Should we trigger a density change event?

**Comment by apaddock** [comment] 2024-02-27 14:39
@cjwinsor any advice on this one? Should this be fixed?

**Comment by cjwinsor** [comment] 2024-04-03 16:01
@apaddock This should be fixed, it most likely is related to state management between the tanstack table and our internal state handling, assuming he are managing that state. If not that we will need to dig a bit deeper.

**Comment by prashanthr6383** [comment] 2024-05-13 09:47
> [@apaddock](https://github.com/apaddock) This is an issue and should be fixed, it most likely is related to state management between the tanstack table and our internal state handling, assuming we are managing that state. If not that we will need to dig a bit deeper.



https://github.com/trimble-oss/modus-web-components/assets/168108000/70f29dc0-b241-46fb-958f-b7b5dc3e2b13

@cjwinsor The problem seems to be with the storybook. I have tested it in my local and it seems to be working fine. 
The issue occurs not only with density changes but with all control items.

**Comment by cjwinsor** [comment] 2024-05-23 14:21
@yohernandez Are you able to reproduce outside of storybook, or was this only identified as an issue in storybook?

**Comment by yohernandez** [comment] 2024-05-23 15:15
@cjwinsor No, I am not. It's probably an issue in Storybook.

**Comment by prashanthr6383** [comment] 2024-05-27 12:45
@cjwinsor In the modus table component, a watch decorator is used for `rowSelectionOptions` which is causing this problem. To resolve this, we can leave the `preSelected` row as [] in the storybook or we can remove this function ?



![Image](https://github.com/trimble-oss/modus-web-components/assets/168108000/78e6999e-b6cd-4dd1-80a5-8281f76fb57e)

modus-table.tsx

**Comment by cjwinsor** [comment] 2024-05-28 22:02
@prashanthr6383 Can you explain more about leaving `preSelected` row as `[]`? Do you mean how its set in the storybook?

**Comment by prashanthr6383** [comment] 2024-06-12 07:52
@cjwinsor Yes.  Whenever a property gets changed, the storybook updates all the properties instead of just the ones that we need. This is why when we change other properties in the storybook, it updates a particular property and sets the default values for the remaining properties.


In our case we set the `preSelected` value as 0 and if some property gets changed the storybook sets back to the default value. can we remove the preselected value if it is not necessary ?

**Comment by cjwinsor** [comment] 2024-07-19 14:36
Lets see what we can do to correct the behavior in the storybook, seems to be fine outside of storybook.

**Comment by prashanth-offcl** [comment] 2024-08-28 14:12
By default we will set the preselected as [] and add a new example to demonstrate the preselection behavior.

**Closed** 2024-09-06 13:58 UTC
Labels: 1, bug, external-request, team-e-builder
