### ISSUE TITLE
Dropdown: keyboard shortcuts not working

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#2392] opened 2024-04-02 14:41 UTC
REF: https://modus-web-components.trimble.com/?path=/story/components-dropdown--default

- <kbd>Space</kbd> is not working as expected. Space should open (right now need to hold key down)
- <kbd>Enter</kbd> is not working at all.

**Comment by austinoneil** [comment] 2024-04-03 05:59
Issue is being caused by two dropdown toggles happening when keydown happens.  See [this](https://github.com/trimble-oss/modus-web-components/blob/main/stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx#L73) and [this](https://github.com/trimble-oss/modus-web-components/blob/main/stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx#L136).  I have deleted the `onKeyDown` from the div and can confirm that it causes the. desired visual behavior, but does not emit events. The method functionalities for the two linked items need to be "merged" into one.

**Comment by ElishaSamPeterPrabhu** [comment] 2024-04-05 06:51
Closing this issue as its fixed in the PR #2396

**Closed by ElishaSamPeterPrabhu** 2024-04-05 06:51 UTC
Labels: bug, accessibility
