### ISSUE TITLE
Modus Navbar - Add button not opening pop-up menu on `Enter` key press

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1628] opened 2023-08-10 10:21 UTC
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

It looks like pressing <kbd>ENTER</kbd> key on icons added from `buttons` prop not opening the menu pop-up

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

modus

### What is your team/division name ?

modus

### Are you willing to contribute ?

None

**Comment by cjwinsor** [comment] 2024-01-26 15:26
Plan:
- Support both `SPACE` and `ENTER` to open/close
- `ESC` can also close

**Comment by prashanth-offcl** [comment] 2024-10-23 13:05
@ElishaSamPeterPrabhu can you check if the issue is fixed in the Navbar. It looks like Enter is handled, but Space and Escape key is not working as expected.

**Comment by ElishaSamPeterPrabhu** [comment] 2024-10-24 07:57
> @ElishaSamPeterPrabhu can you check if the issue is fixed in the Navbar. It looks like Enter is handled, but Space and Escape key is not working as expected.

The behavior is added for buttons added dynamically 
```
export interface ModusNavbarButton {
  id: string;
  icon: string;
  orderIndex: number;
  hideMenu?: boolean;
  tooltip?: ModusNavbarTooltip;
}
buttons: ModusNavbarButton[];
```

for buttons like help and profile which have boolean properties for their visibility the behavior is not set

**Comment by ElishaSamPeterPrabhu** [comment] 2024-11-15 10:36
> > [@ElishaSamPeterPrabhu](https://github.com/ElishaSamPeterPrabhu) can you check if the issue is fixed in the Navbar. It looks like Enter is handled, but Space and Escape key is not working as expected.
> 
> The behavior is added for buttons added dynamically
> 
> export interface ModusNavbarButton {
>   id: string;
>   icon: string;
>   orderIndex: number;
>   hideMenu?: boolean;
>   tooltip?: ModusNavbarTooltip;
> }
> buttons: ModusNavbarButton[];
> for buttons like help and profile which have boolean properties for their visibility the behavior is not set.

Since the expected behavior this as discussed with @enowak1031 am closing the issue

**Closed by ElishaSamPeterPrabhu** 2024-11-15 10:36 UTC
Labels: priority:medium, bug, good-first-issue, accessibility, modus-navbar
