### ISSUE TITLE
Table: add a maxWidth to the row actions column

### ISSUE THREAD

**Issue by leosole-trimble** [trimble-oss/modus-web-components#2753] opened 2024-08-05 12:57 UTC
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

For tables with a small number of columns, the row actions column might become too large, and there is no way of controlling it, since there are no width properties the user can set.
This column could have a fixed width calculated by the number of actions in it. This already happens for tables with lots of columns, the row actions are fixed at the end of the row with a pre calculated width

Few columns and unnecessary large row actions width:
![image](https://github.com/user-attachments/assets/a055996e-6887-4d78-a3b7-5f14bbd781ab)

Lots of columns and fixed width:
![image](https://github.com/user-attachments/assets/2000d2ea-38f6-4920-9d5f-83ccafb5cc99)

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

Trimble Inspections

### What is your team/division name ?

Camaleão/Transportation

### Are you willing to contribute ?

No

**Comment by prashanth-offcl** [comment] 2024-08-14 14:11
@prashanth-offcl to check and decide the prop name to allow the integrator to set the column width.

**Comment by prashanth-offcl** [comment] 2024-08-21 10:52
Related to #1922

**Comment by prashanth-offcl** [comment] 2024-10-01 06:47
Duplicate of 1922

**Closed by prashanth-offcl** 2024-10-01 06:47 UTC
Labels: modus-table, external-request
