### ISSUE TITLE
Support various number of buttons in modal

### ISSUE THREAD

**Issue by davidtsilcock** [trimble-oss/modus-web-components#1304] opened 2023-05-17 23:40 UTC
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Proposal

Being able to add more than two buttons into a modus-modals would be great. 
![Screenshot 2023-05-17 095801](https://github.com/trimble-oss/modus-web-components/assets/106724479/861c0ae7-624f-43b9-8fad-040ed2fb1246)

I(t would also be helpful to have the option to only have one button in the modal. 
![OLD-single-button (12)](https://github.com/trimble-oss/modus-web-components/assets/106724479/37382cfd-787a-4c6a-a820-04c0280f4916)

### Which npm package?

@trimble-oss/modus-web-components

### Priority

Medium

### What is the product name the feature is requested for?

Trimble Creator

### What is the team name the product belongs to?

Nexus

### What is the division name the team belongs to?

Construction

**Comment by msankaran0712** [comment] 2023-05-18 13:44
cc @davidtsilcock 
For additional information, https://docs.google.com/document/d/1e3ilHfEdIDAm4s4811iLnF-4H2RTyIHKQrRMF8p74RQ/edit#heading=h.lf66jh7nizs8

**Comment by msankaran0712** [comment] 2023-06-02 09:22
@davidtsilcock looks like we can have a single button. Can you please check with your dev team on that?

**Comment by msankaran0712** [comment] 2023-06-02 09:23
@enowak1031 @egunther39 @coliff @soniakaukonen 
we need to decide if we should support more than two modal buttons and the coloring of the buttons as shown in the screenshot above.

**Comment by soniakaukonen** [comment] 2023-06-06 00:21
@msankaran0712 @enowak1031 - something worth informing the Tiger team?

**Comment by davidtsilcock** [comment] 2023-06-06 02:04
@msankaran0712 Agreed about the button placement. We'll adjust these when we convert our current modals to web components.

@soniakaukonen I have sent a message to Eric regarding this. He will bring it up, along with https://github.com/trimble-oss/modus-web-components/issues/1305 in the tiger team meeting tomorrow.

**Comment by msankaran0712** [comment] 2023-06-07 10:40
@davidtsilcock will your team be able to contribute?

**Comment by davidtsilcock** [comment] 2023-06-07 22:02
Yep, we should be able to! I've added it to our JIRA board so it'll be discussed in the next grooming session early next week.

**Comment by msankaran0712** [comment] 2023-06-21 08:14
This is to reaffirm that the Modus has approved the functionality with a revision `https://github.com/trimble-oss/modus-web-components/issues/1304#issuecomment-1573842398`. 


cc @davidtsilcock

**Comment by davidtsilcock** [comment] 2023-06-21 08:32
Yup, a fair revision. Have folded that into our spec. Our story outlining the changes can be found here https://jira.trimble.tools/browse/CREATOR-1957. When this story is done, we will contribute it back to Modus.

**Comment by msankaran0712** [comment] 2023-09-22 15:18
hey @davidtsilcock just an update, @egunther39 @soniakaukonen confirmed me that the Modal can accept three buttons in the order from left to right -> outline, secondary, primary

**Comment by davidtsilcock** [comment] 2023-09-25 02:55
It can accept it currently? Or is that how you'd want us to contribute it back.

**Comment by msankaran0712** [comment] 2023-09-25 05:44
hey @davidtsilcock That functionality is not available on the component yet, it will be part of the contribution.

**Comment by msankaran0712** [comment] 2023-10-19 14:51
hey @davidtsilcock We now support custom footer for Modals, it was added from this PR https://github.com/trimble-oss/modus-web-components/issues/1728. This means you can have three buttons in the Modal as long as it follows the recommended button progressions.
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/ec92551a-ebf9-4427-90b0-eba96da350d2)

**Closed by msankaran0712** 2023-10-19 14:51 UTC
Labels: external-request, team-trimble-creator, modus-approved, contribution
