### ISSUE TITLE
Table web component row checkbox over cell text 

### ISSUE THREAD

**Issue by carlos-amadeo** [trimble-oss/modus-web-components#2862] opened 2024-09-12 13:46 UTC
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

The row checkbox displays over the cell text instead of next to it.
![image](https://github.com/user-attachments/assets/6263bbf5-0f28-4577-aed3-2809c2b7f6e9)

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

e-Builder

### What is your team/division name ?

UX team

### Are you willing to contribute ?

None

**Comment by prashanth-offcl** [comment] 2024-09-16 12:05
Duplicate of #2818

**Closed by prashanth-offcl** 2024-09-16 12:05 UTC
Labels: bug, external-request
