### ISSUE TITLE
Navbar add additional App 

### ISSUE THREAD

**Issue by jmecosta** [trimble-oss/modus-web-components#1638] opened 2023-08-14 07:02 UTC
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Hi,

Looks i cant configure the Navbar to add App in front on Trimble. 

<img width="1871" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/1041352/479ecc31-a0f4-4edc-84d0-dc85df7f2432">

This is quite common for Trimble Applications. the avatar, i think its currently under proposal so would be nice to get it as soon as possible. 

Thanks

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

Trimble Desktop

### What is your team/division name ?

Tekla Team

### Are you willing to contribute ?

None

**Comment by msankaran0712** [comment] 2023-08-22 07:12
@jmecosta Thank you for submitting the issue. Kindly let us know if your team is interested in fixing the issue.

**Comment by jmecosta** [comment] 2023-08-22 07:40
@msankaran0712 yes we can contribute

**Comment by msankaran0712** [comment] 2023-08-22 07:53
Thank you @jmecosta

**Comment by jmecosta** [comment] 2023-08-23 14:23
For now it's only a text without interaction.  But u see other wanting to
add a log also.

Example Trimble Tekla with both product icons

**Comment by msankaran0712** [comment] 2023-09-13 14:28
@jmecosta It is okay to hide the profile icon if no TID implementation.

**Comment by msankaran0712** [comment] 2023-09-13 14:32
@jmecosta the issue is approved and ready to be worked on

**Comment by msankaran0712** [comment] 2023-09-20 14:10
@enowak1031 to check with Branding team whether it is okay to display "Trimble Logo | Product Logo | Application Logo "

**Comment by msankaran0712** [comment] 2023-10-13 14:50
@jmecosta A separate issue has been created for making the profile menu optional, https://github.com/trimble-oss/modus-web-components/issues/1782
Anybody who is interested can contribute a PR 👍🏼

**Comment by msankaran0712** [comment] 2023-11-08 14:54
Only one logo is allowed in the navbar

**Comment by cjwinsor** [comment] 2024-04-05 14:41
@jmecosta The profile menu is now optional. Use the `showProfile` property set to `false` to hide.  With the logo, the current guidance is to have a combined logo following the branding guidance.  Due to this, I will be closing this ticket.

**Closed by cjwinsor** 2024-04-05 14:41 UTC
Labels: external-request, modus-approved, team-trimble-desktop-tekla
