### ISSUE TITLE
Modus Side navigation(React component) push mode is not working as expected 

### ISSUE THREAD

**Issue by VinoSakthiv** [trimble-oss/modus-web-components#1706] opened 2023-09-07 07:24 UTC
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Modus Side Navigation(React component) push mode is not working as expected . margin is not applied to target content
steps to reproduce:

-  create a side navigation component with mode="push"
<ModusSideNavigation 
          data={menuItems}
          expanded={isOpen}
          maxWidth={'300'}
          mode="push"
          target-content="#appcontent"
        />
Margin should be added so the content is pushed to the right 

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.1.52-react17

### Priority

High

### What product/project are you using Modus Components for ?

Trimble Construction Cloud

### What is your team/division name ?

Industry Clouds

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

no

**Comment by msankaran0712** [comment] 2023-09-07 07:34
As discussed with @VinoSakthiv, it happens only on React but works fine on the web component.
[myiframetest.zip](https://github.com/trimble-oss/modus-web-components/files/12545999/myiframetest.zip)

**Comment by cjwinsor** [comment] 2024-02-05 15:05
@cjwinsor Take a look at the reproduction with latest Modus.

**Comment by cjwinsor** [comment] 2024-04-19 13:53
Investigate to see if still occurring in latest version. If it is, then continue with fixing.  Otherwise, we will close this ticket.

**Comment by prashanthr6383** [comment] 2024-05-06 13:35
> Investigate to see if still occurring in latest version. If it is, then continue with fixing. Otherwise, we will close this ticket.

Hi @cjwinsor I have tested the latest modus in the React and it seems to be working correctly. 

https://github.com/trimble-oss/modus-web-components/assets/168108000/86a69bd9-594b-4e6d-914e-f3413b7f6ba7

**Closed** 2024-05-09 14:20 UTC
Labels: 2, priority:high, bug, react, external-request, modus-approved, team-industry-clouds
