### ISSUE TITLE
File Upload Dropzone in Web Components

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#425] opened 2022-04-12 15:58 UTC
As an engineer, I want to have the file upload dropzone component available in web components, so I can use it in my application. 

REF: https://modus.trimble.com/components/file-upload-dropzone/

**Comment by coliff** [comment] 2022-04-12 16:02
duplicate of #421
(I copied across the text and labels)

**Closed by coliff** 2022-04-12 16:02 UTC
Labels: priority:medium, new-component, story
