### ISSUE TITLE
Add header footer modal divider options in web components

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus-web-components#992] opened 2023-01-30 18:09 UTC
There should be an option to hide the dividers to support certain use cases.

![Image](https://user-images.githubusercontent.com/101354258/215560138-4d21c329-06bc-4905-92f0-44b5527fd24d.png)

**Comment by coliff** [comment] 2023-01-30 23:27
Closing as Duplicate of https://github.com/trimble-oss/modus-web-components/issues/854

**Closed** 2023-03-03 15:24 UTC
Labels: bug
