### ISSUE TITLE
Autocomplete Web component - Keyboard accessibility - When the user hit on up and down arrow keys on the keyboard, dropdown list items is not selected

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1282] opened 2023-05-12 15:22 UTC
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

[BUG] Autocomplete Web component - Keyboard accessibility - When the user hit on up and down arrow keys on the keyboard, dropdown list items is not selected

**Steps to reproduce the behavior on Canvas section:**

1. Go to Autocomplete web component
2. Click on Canvas section
3. Hit on tab key on the keyboard
4. Autocomplete search textbox should be selected
5. Enter letter A in the textbox
6. Dropdown list should be displayed
7. Hit on Up and Down arrow keys to select the drop down list items
8. Dropdown list items is not selected accordingly

**Expected behavior**
The first item in the dropdown list should be preselected and when user hit on up and down arrow keys on the keyboard, the list of items on the dropdown should be selected accordingly

**Current behavior**
The list of items is not selected when the user hit on up and down arrow keys on the keyboard

Please refer the below screenshot:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/5e19f71f-ddbe-4328-bb3c-254db69a3c61)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### Priority

Low

### What product/project are you using Modus Components for?

QA

### What is your team/division name?

QA

**Comment by msankaran0712** [comment] 2023-08-10 15:46
Duplicate of #979

**Closed by msankaran0712** 2023-08-10 15:46 UTC
Labels: 3, bug, modus, QA
